### ISSUE TITLE
Nicht mehr aktuell

### ISSUE THREAD

**Issue by solidevolution** [BjoernSchotte/commerce-dev-environment#5]
Clone of 'git://github.com/camptocamp/puppet-common' into submodule path 'puppet/modules/common' failed

Am besten commerce-dev-environment aktualisieren oder die Leiche richtig killen ;)

**Comment by BjoernSchotte** [comment]
Can you send a pull request to fix it? Thanks.

**Comment by solidevolution** [comment]
Sorry but its more effective to do it completely new. Most of the used puppet modules are out of date.
